[package]
name = "ein"
version = "0.1.0"
authors = ["Joe Clay <27cupsofcoffee@gmail.com>"]

[dependencies]
ein_syntax = { path = "ein_syntax" }
ein_treewalk = { path = "ein_treewalk" }

structopt = "0.2.5"
rustyline = "1.0.0"

[workspace]
members = ["ein_syntax", "ein_treewalk"]
