[package]
name = "ein_syntax"
version = "0.1.0"
authors = ["Joe Clay <27cupsofcoffee@gmail.com>"]
edition = "2018"

[dependencies]
lalrpop-util = "0.16.3"
failure = "0.1.5"

[build-dependencies]
lalrpop = "0.16.3"
